[package]
name = "e2e"
version = "0.0.0"
edition = "2024"

[features]
default = []

# Several tests are pretty heavyweight and so are disabled by default; this
# feature enables all tests for maximal correctness.
ci = []

[dependencies]
bon.workspace = true
cargo_metadata.workspace = true
color-eyre.workspace = true
escargot = { workspace = true }
tempfile.workspace = true
tracing.workspace = true

[dev-dependencies]
itertools.workspace = true
pretty_assertions.workspace = true
simple_test_case = { workspace = true }
test-log.workspace = true
