[package]
name = "e2e"
version = "0.1.0"
edition = "2024"

[features]
default = []

# Several tests are pretty heavyweight and so are disabled by default; this
# feature enables all tests for maximal correctness.
ci = []

[dependencies]
bon.workspace = true
cargo_metadata.workspace = true
color-eyre.workspace = true
escargot = { workspace = true }
location-macros.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tempfile.workspace = true
tracing.workspace = true

[dev-dependencies]
itertools.workspace = true
pretty_assertions.workspace = true
simple_test_case = "1.3.0"
test-log.workspace = true
