[package]
name = "courier"
version = "0.0.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tower = { version = "0.5", features = ["buffer", "limit", "load-shed"] }
tower-http = { version = "0.6", features = ["trace", "limit", "timeout", "compression-full", "decompression-full"] }
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "migrate"] }
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
async-compression = { version = "0.4", features = ["tokio", "zstd"] }
blake3 = "1"
hex = "0.4"
zstd = "0.13"
color-eyre = "0.6"
thiserror = "2"
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tree = { version = "0.4", features = ["time"] }
clap = { version = "4", features = ["derive", "env"] }
atomic-time = "0.1"
tap = "1"
derive_more = { workspace = true, features = ["full"] }
async-tempfile = "0.7.0"
tempfile = "3"
uuid = { workspace = true, features = ["v4"] }
aerosol = { version = "1.3.0", features = ["async", "axum", "axum-extra", "tracing"] }
futures = "0.3"
secrecy = { version = "0.10.3", features = ["serde"] }
block-id = "0.2.1"
const-str = { workspace = true, features = ["all"] }
hashlru = "0.11.1"
rusty_paseto = "0.7.2"
rand = "0.9.2"

[dev-dependencies]
axum-test = { version = "18.1.0", features = ["all"] }
pretty_assertions = "1"
proptest = "1.8.0"
serde_json.workspace = true
simple_test_case.workspace = true
tempfile = "3"
test-log = { version = "0.2", features = ["trace"] }
test-strategy = "0.4.3"
